In [1]:
import torch

- a * b 矩阵按位相乘，要求：矩阵shape相同
- torch.matmul(a, b)  == a @ b(完全等价) 矩阵相乘，支持broadcast；要求：a的列数等于b的行数
    - torch.dot():1d,不支持broadcast  （子集）
    - torch.mm():2d,不支持broadcast 要求：a的列数等于b的行数
    - torch.bmm():3d batch,不支持broadcast 要求：第一维的batch必须相同，按第一维展开后的shape满足：a的列数等于b的行数

In [2]:
a = torch.tensor([2,3])

In [3]:
b = torch.tensor([2,1])

In [5]:
a.dot(b)

tensor(7)

In [6]:
torch.dot(a,b)

tensor(7)

In [7]:
a@b

tensor(7)

In [8]:
torch.matmul(a,b)

tensor(7)

In [ ]:
a * b #[2*2,3*1]

tensor([4, 3])

In [10]:
mat1 = torch.randn(2,3)

In [11]:
mat2 = torch.randn(3,3)

In [12]:
mat2

tensor([[-0.3141,  2.1072,  0.0137],
        [ 0.7974, -0.5378, -0.0806],
        [ 0.9115, -0.0333, -1.6266]])

In [13]:
mat1

tensor([[-0.2927,  0.3170,  0.6755],
        [ 1.0018, -0.9842, -0.2831]])

In [14]:
torch.mm(mat1,mat2)

tensor([[ 0.9604, -0.8097, -1.1283],
        [-1.3575,  2.6497,  0.5536]])

In [15]:
torch.matmul(mat1,mat2)

tensor([[ 0.9604, -0.8097, -1.1283],
        [-1.3575,  2.6497,  0.5536]])

In [16]:
mat1 @ mat2

tensor([[ 0.9604, -0.8097, -1.1283],
        [-1.3575,  2.6497,  0.5536]])

In [17]:
input = torch.randn(2,3,4)

In [18]:
mat3 = torch.randn(2,4,5)

In [19]:
torch.bmm(input,mat3)

tensor([[[-0.5496,  0.8799,  2.1138, -0.7615, -0.4350],
         [ 1.2712,  1.2324, -1.6242,  1.7839,  0.9475],
         [ 1.4447,  0.4004, -1.3616,  1.9769, -0.0675]],

        [[ 4.0265,  1.4014,  1.9333,  1.3998, -4.1329],
         [ 0.5957,  0.5290, -0.6335,  1.0413, -0.3238],
         [ 3.2690,  2.5884,  0.5076,  0.7277, -2.0497]]])

In [20]:
torch.matmul(input,mat3)

tensor([[[-0.5496,  0.8799,  2.1138, -0.7615, -0.4350],
         [ 1.2712,  1.2324, -1.6242,  1.7839,  0.9475],
         [ 1.4447,  0.4004, -1.3616,  1.9769, -0.0675]],

        [[ 4.0265,  1.4014,  1.9333,  1.3998, -4.1329],
         [ 0.5957,  0.5290, -0.6335,  1.0413, -0.3238],
         [ 3.2690,  2.5884,  0.5076,  0.7277, -2.0497]]])

In [21]:
input @ mat3

tensor([[[-0.5496,  0.8799,  2.1138, -0.7615, -0.4350],
         [ 1.2712,  1.2324, -1.6242,  1.7839,  0.9475],
         [ 1.4447,  0.4004, -1.3616,  1.9769, -0.0675]],

        [[ 4.0265,  1.4014,  1.9333,  1.3998, -4.1329],
         [ 0.5957,  0.5290, -0.6335,  1.0413, -0.3238],
         [ 3.2690,  2.5884,  0.5076,  0.7277, -2.0497]]])

In [22]:
for i in range(2):
    print(torch.mm(input[i,:,:],mat3[i,:,:]))

tensor([[-0.5496,  0.8799,  2.1138, -0.7615, -0.4350],
        [ 1.2712,  1.2324, -1.6242,  1.7839,  0.9475],
        [ 1.4447,  0.4004, -1.3616,  1.9769, -0.0675]])
tensor([[ 4.0265,  1.4014,  1.9333,  1.3998, -4.1329],
        [ 0.5957,  0.5290, -0.6335,  1.0413, -0.3238],
        [ 3.2690,  2.5884,  0.5076,  0.7277, -2.0497]])


In [23]:
A = torch.randn(3, 4)
x = torch.randn(4) 
y = A @ x  


In [25]:
A

tensor([[ 0.8465,  1.7365, -0.1117, -0.8887],
        [ 0.1683, -0.3218,  0.9915, -0.8987],
        [-0.6140,  0.4684,  0.6307, -0.0406]])

In [27]:
0.8465*(-0.7986)+1.7365*(-1.3096)+(-0.1117)*1.3174+(-0.8887)*0.1473

-3.22819439

In [26]:
x

tensor([-0.7986, -1.3096,  1.3174,  0.1473])

In [24]:
y

tensor([-3.2281,  1.4609,  0.7018])

这里的 broadcast（广播） 指的是：当参与运算的张量在某些维度上大小不一致时，PyTorch 会按规则**把某些维度为 1 的那一方“虚拟扩展（expand）”**到匹配的大小，从而让运算能一次性在“批维/前置维”上并行进行；这个扩展通常不是真拷贝数据，而是视图层面的“重复使用”。
1) torch.matmul(a, b) / a @ b 的广播：广播的是“批维（前置维）”
对于高维（... 表示若干前置维）：

a 形状：(..., m, k)
b 形状：(..., k, n)
输出：(..., m, n)
其中 ... 这些前置维会按 broadcasting 规则对齐；最后两维 (m,k) 和 (k,n) 仍必须满足矩阵乘法条件：k 相等。

例 1：b 没有 batch 维，自动广播到每个 batch
python
a = torch.randn(10, 3, 4)  # (batch=10, m=3, k=4)
b = torch.randn(4, 5)      # (k=4, n=5)

y = a @ b                  # -> (10, 3, 5)
理解：把 b 视作 (1, 4, 5)，广播成 (10, 4, 5) 后，对 10 个 batch 分别做矩阵乘法。

例 2：双方都有 batch 维，但某一方 batch=1，被广播
python
a = torch.randn(2, 1, 3, 4)  # (...=2,1, m=3, k=4)
b = torch.randn(1, 7, 4, 5)  # (...=1,7, k=4, n=5)

y = a @ b                    # -> (2, 7, 3, 5)
这里前置维分别是 (2,1) 和 (1,7)，广播结果是 (2,7)。

2) 为什么 mm / bmm 说“不支持 broadcast”
torch.mm(a, b)：只接受 2D，不存在“批维”可广播
python
a = torch.randn(10, 3, 4)
b = torch.randn(4, 5)
torch.mm(a, b)  # 报错：a 不是 2D
torch.bmm(a, b)：只接受 3D，且 batch 维必须完全相同
python
a = torch.randn(10, 3, 4)  # (batch=10, m=3, k=4)
b = torch.randn(1, 4, 5)   # (batch=1,  k=4, n=5)

torch.bmm(a, b)            # 报错：batch 维 10 != 1（不会帮你广播）
但同样的形状用 matmul 可以：

python
a @ b  # b 会被广播到 batch=10，结果 (10, 3, 5)
3) 一句话总结
matmul/@：会对**前置维（batch 维）**做广播；最后两维仍需满足矩阵乘法的 
k
k 对齐。
mm：2D 专用，无广播。
bmm：3D batch 专用，但 batch 维必须相同，无广播。